import { ContentItem } from "./Icontent-item";

export const CONTENT_LIST: ContentItem[] = [
    {
        title: 'Introdução',
        text: "Os planetas rochosos são os quatro planetas mais próximos do Sol: <strong>Mercúrio, Vênus, Terra e Marte</strong>. Eles são formados principalmente por rochas e metais, e têm uma superfície sólida. <br><br> Os planetas rochosos são muito diferentes uns dos outros. Mercúrio é um planeta pequeno e quente, com uma superfície coberta de crateras. Vênus é um planeta quente e úmido, com uma atmosfera espessa de dióxido de carbono. A Terra é o único planeta do Sistema Solar conhecido por abrigar vida, e por ter água líquida em sua superfície. Marte é um planeta frio e seco, com uma atmosfera fina.<br><br>A exploração desses planetas é uma área de pesquisa ativa, e os cientistas esperam aprender mais sobre a sua formação, evolução e potencial para a vida."
    },
    {
        title: 'Mercúrio',
        text: 'Mercúrio é o planeta mais próximo do Sol e o menor planeta do Sistema Solar, sendo um pouco maior que a Lua da Terra, e não possui satélites naturais (luas), nem anéis.<br><br>O planeta é extremamente quente, podendo atingir temperaturas de 430ºc no lado iluminado pelo sol (dia), mas durante a noite as temperaturas caem bruscamente, atingindo cerca de -180ºc, tendo assim a maior amplitude térmica entre os planetas do sistema solar. Apesar das altas temperaturas e sua proximidade com o Sol, não é o planeta mais quente do sistema solar.<br><br>A superfície de Mercúrio é cheia de crateras, formadas por impactos de meteoritos, e não é um planeta propício à abrigar vida como conhecemos, pois não possui atmosfera para proteger dos raios solares. Um ano em Mercúrio tem 88 dias, e cada dia é equivalente a 59 dias terrestres.'
    },
    {
        title: 'Vênus',
        text: 'Vênus é o segundo planeta mais próximo do Sol e o mais quente do Sistema Solar, com temperaturas que chegam a quase 500ºc. Graças à sua atmosfera espessa, composta principalmete por dióxido de carbono, o planeta retém calor e forma um grande efeito estufa. Além disso, o planeta é conhecido como "gêmeo da Terra", e possui vários vulcões e montanhas, mas não possui satélites naturais.<br><br>Apesar de extremamente quente, cerca de 50km acima da superfície do planeta, as temperaturas variam de 30 a 70ºc, e a pressão atmosférica é semelhante à da Terra, tornando provável que o planeta possa abrigar vida terrestre, como alguns micróbios, porém, até hoje não há evidências o suficiente para afirmar que o planeta abriga vida.<br><br>Algumas sondas chegaram a pousar em sua superfície, mas nenhuma sobrevive às altas temperaturas e pressão atmosférica, algumas funcionaram brevemente após o pouso, mas duraram cerca de 20 minutos a 2 horas, no máximo. A sonda Venera-9, lançada pela União Soviética em 1975, registrou a imagem abaixo (a imagem original é em preto e branco), da superfície do planeta, uma paisagem escura e rochosa, com um céu provavelmente amarelo enxofre.',
        image: 'https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2023/03/estas-son-unicas-fotos-existen-superficie-venus-buena-razon-2991728.jpg?tf=3840x'
    },
    {
        title: 'Terra',
        text: 'A Terra é o terceiro planeta mais próximo do Sol e o único planeta do Sistema Solar conhecido por abrigar vida, tem uma atmosfera composta principalmente de nitrogênio e oxigênio, e possui as condições ideais de temperatura, pressão, atmosfera e distância do Sol para abrigar vida, é uma matemática exata. <br><br>A superfície da Terra é coberta por oceanos, continentes, montanhas e planícies, e é o planeta mais estudado e monitorado pela NASA. No menu "Terra" exploramos um pouco mais sobre ele.'
    },
    {
        title: 'Marte',
        text: 'Marte é o quarto planeta mais próximo do Sol e o segundo menor planeta do Sistema Solar. A temperatura de Marte é uma das mais próximas da Terra, variando de -87°C a 20°C, porém, ainda é um planeta inóspito para abrigar vida, devido não somente à temperatura fria, mas também à sua atmosfera fina, que não protege a superfície dos raios solares, e é composta principalmente por dióxido de carbono, argônio e nitrogênio. O planeta possui duas luas: Fobos e Deimos.<br><br>Marte é um planeta que desperta grande interesse científico. Os cientistas acreditam que Marte já foi um planeta mais quente e úmido, e que pode ter abrigado vida no passado. Algumas formações na superfície indicam que Marte pode ter tido até mesmo rios e água em estado líquido na superfície. A exploração de Marte começou na década de 1960. Desde então, várias missões espaciais foram enviadas ao planeta, financiadas por diferentes agências espaciais, essas missões nos proporcionaram uma grande galeria de fotos de Marte, como esta, registrada pela câmera de bordo do rover Perseverance, da NASA, no dia 3 de janeiro de 2024.',
        image: 'https://mars.nasa.gov/mars2020-raw-images/pub/ods/surface/sol/01021/ids/edr/browse/ncam/NRF_1021_0757581300_130ECM_N0490370NCAM03021_02_095J01_800.jpg'
    },
]