import { ContentItem } from "../../default/default-page/Icontent-item";

export const CONTENT_LIST: ContentItem[] = [
  {
    title: 'Introdução',
    text: 'Os planetas gasosos são os quatro planetas mais distantes do Sol: <strong>Júpiter, Saturno, Urano e Netuno</strong>. Esses planetas se diferenciam dos rochosos por sua estrutura predominantemente composta por gases, e pela ausência de uma superfície sólida definida. Apesar de não possuírem uma superfície, os planetas gasosos possuem um núcleo sólido em seu centro, mas a maior parte de sua massa está distribuída em suas extensas camadas gasosas.<br><br> Cada planeta possui características únicas e incríveis. Júpiter, o maior deles, exibe uma atmosfera turbulenta com suas tempestades, como a famosa Grande Mancha Vermelha. Saturno é conhecido por seus deslumbrantes anéis, compostos principalmente de partículas de gelo e rocha. Urano e Netuno, por sua vez, possuem atmosferas azuladas devido à presença de metano em suas composições. Uma característica comum desses planetas, é que todos possuem anéis, apesar de não serem tão aparentes quanto os de Saturno.<br><br> Esses planetas desempenham papéis cruciais na dinâmica do sistema solar, influenciando a evolução e distribuição dos outros corpos celestes.',
  },
  {
    title: 'Júpiter',
    text: 'Júpiter é o maior planeta do sistema solar, é mais de 11 vezes maior que a Terra e possui uma massa cerca de 318 vezes maior. Sua atmosfera consiste principalmente de hidrogênio e hélio, contribuindo para as faixas distintas de nuvens visíveis em sua superfície. Além do seu tamanho, o planeta se destaca pela Grande Mancha Vermelha, uma tempestade que perdura há seculos, e chega a ser maior que a Terra, mostrando um pouco do clima turbulento do planeta, que abriga ventos intensos, o que torna Júpiter pouco provável para abrigar vida como conhecemos.<br><br>O planeta possui atualmente 95 luas reconhecidas pela União Astronômica Internacional, sendo as quatro maiores chamadas de luas galileanas: Io, Europa, Ganimedes e Calisto. Cada uma dessas luas tem características únicas, como vulcões ativos, oceanos subterrâneos e possíveis condições propícias para a busca de vida, a lua Europa, por exemplo, é considerado o local mais provável a abrigar vida no Sistema Solar, além da Terra.<br><br>A NASA explorou Júpiter por meio de várias missões espaciais, incluindo a sonda Galileu, que proporcionou valiosas descobertas nos anos 1990. Em 2016, a sonda Juno chegou a Júpiter, e continua em órbita até os dias atuais, fornecendo informações cruciais sobre a atmosfera, magnetosfera e estrutura interna do planeta.',
  },
  {
    title: 'Saturno',
    text: 'Saturno é o sexto planeta do Sistema Solar, e também o segundo maior, perdendo apenas para o gigante Júpiter. A atmosfera de Saturno é principalmente composta por hidrogênio e hélio, com traços de metano, amônia, vapor d água e outros compostos. Essa composição atmosférica confere a Saturno suas cores marcantes, predominantemente amarela devido às partículas de amônia presentes.<br><br>Saturno é famoso por seus impressionantes anéis, que são compostos principalmente de pequenos pedaços de gelo e poeira. Esses anéis são subdivididos em várias faixas distintas e proporcionam um espetáculo visual único. Ao todo, até o dia de hoje, o planeta possui 146 luas reconhecidas, sendo um lar de diferentes mundos, intrigantes e únicos. A maior lua de Saturno é Titã, que é maior do que o planeta Mercúrio e possui uma atmosfera densa. A missão Cassini contribuiu para a exploração de Titã, fornecendo informações cruciais sobre sua superfície e composição atmosférica. Outras luas notáveis incluem Encélado, conhecida por seus gêiseres de água e a lua Mimas, que apresenta uma enorme cratera em forma de olho chamada Herschel. <br><br> Em relação às missões espaciais, a Cassini não foi a única a explorar Saturno. A sonda Pioneer 11 foi a primeira a sobrevoar o planeta em 1979, seguida pelas missões Voyager 1 e 2 na década de 1980. Cada missão contribuiu significativamente para nossa compreensão sobre o planeta e seus satélites naturais.'
  },
  {
    title: 'Urano',
    text: 'Urano é o sétimo planeta a partir do Sol em nosso sistema solar e possui características únicas que o distinguem dos demais. O planeta é conhecido por sua inclinação peculiar, girando em um ângulo de 90º em relação ao plano de sua órbita. Essa inclinação extrema sugere que, possivelmente, Urano foi atingido por um objeto massivo no passado, resultando em sua rotação única.<br><br>O planeta é composto principalmente por hidrogênio e hélio, com uma atmosfera que contém traços de metano, que lhe conferem uma tonalidade azul-esverdeada característica. As condições atmosféricas em Urano são extremamente dinâmicas, com ventos que podem atingir velocidades superiores a 900 km/h. A NASA, até os dias atuais não lançou missões específicas para explorar Urano, embora hajam propostas para futuras explorações. Apenas uma missão visitou o distante Urano, a Voyager 2, lançada em 1977, com o objetivo de explorar o espaço distante, hoje a sonda está fora do Sistema Solar, e a missão continua ativa. Além das informações da Voyager, o que se sabe sobre o planeta foi estudado através de telescópios.<br><br>Urano possui 27 luas reconhecidas, cada uma com suas características únicas. As maiores luas são Titânia, Oberon, Umbriel, Ariel e Miranda. Titânia é a maior delas, superando a lua da Terra, com uma superfície marcada por crateras, vales e outras formações geológicas intrigantes. Oberon, por sua vez, destaca-se por possuir uma das superfícies mais escuras entre as luas de Urano. A diversidade dessas luas fornece informações valiosas sobre a história e a formação do sistema uraniano, mesmo que missões diretas ainda não tenham sido realizadas até o momento. <br><br>A imagem abaixo, registrada pelo telescópio Hubble, da NASA, mostra a inclinação do planeta, e seus anéis.',
    image: 'https://images-assets.nasa.gov/image/0301099/0301099~large.jpg?w=1920&h=1772&fit=clip&crop=faces%2Cfocalpoint'
  },
  {
    title: 'Netuno',
    text: 'Netuno é o oitavo e último planeta do Sistema Solar, e o único não visível no céu a olho nu. Em 2011, Netuno completou sua primeira órbita de 165 anos desde sua descoberta em 1846, ou seja, um ano no planeta equivale a 165 anos terrestres. A atmosfera de Netuno é caracterizada por ventos extremamente fortes, atingindo velocidades superiores a 2.000 km/h, e o planeta possui um clima extremamente frio, com temperaturas que chegam a -220ºc. Essa intensa atividade atmosférica cria tempestades notáveis, como a Grande Mancha Escura, uma enorme tempestade que foi observada pela primeira vez em 1989 pela sonda Voyager 2. Outra característica intrigante é o seu campo magnético, que é cerca de 27 vezes mais forte que o da Terra.<br><br>Netuno possui até o momento 14 satélites naturais reconhecidos, sendo Tritão o maior deles. Tritão é notável por sua órbita retrógrada, movendo-se em sentido oposto à rotação do planeta. Além disso, sua superfície é coberta por uma fina camada de nitrogênio e gelo, contribuindo para um ambiente geologicamente ativo.<br><br>A única missão a explorar Netuno também foi a Voyager 2, que coletou informações importantes sobre sua atmosfera, luas e características magnéticas. A distância do planeta em relação à Terra torna difícil o envio de missões até lá, porém, o planeta também é um tópico de grande interesse na pesquisa espacial.'
  },
];
