import { ContentItem } from '../../default/default-page/Icontent-item';

export const CONTENT_LIST: ContentItem[] = [
  {
    title: 'Introdução',
    text: 'O Sol é uma estrela localizada no centro do nosso sistema solar, sendo uma fonte primária de luz e calor para a Terra. Composta principalmente de hidrogênio e hélio, a estrela realiza constantes reações nucleares, convertendo hidrogênio em hélio e liberando uma enorme quantidade de energia no processo. Essa energia é emitida na forma de luz e calor, que atinge a Terra e é essencial para a sustentação da vida. O Sol possui uma massa aproximadamente 330 mil vezes maior que a da Terra e exerce uma força gravitacional que mantém todos os planetas e outros corpos celestes do sistema solar em órbita ao seu redor.<br><br>Apesar de gigante e muito importante para nós, o Sol é uma estrela anã amarela, e existem bilhões de outras estrelas como essa em nossa galáxia.',
  },
  {
    title: 'Anã Amarela',
    text: 'Conforme dito anteriormente, o Sol é classificado como uma estrela anã amarela, uma categoria que descreve estrelas de tamanho médio em comparação com a vastidão do universo. As estrelas anãs amarelas, como o nosso Sol, pertencem à sequência principal, uma fase de vida em que a estrela converte hidrogênio em hélio por meio de fusão nuclear em seu núcleo, permitindo a estabilidade necessária para sustentar a vida na Terra.<br><br>Características das estrelas anãs amarelas incluem uma temperatura superficial que varia de aproximadamente 5.500 a 6.000ºc, o que contribui para a cor amarela visível. Além disso, essas estrelas geralmente têm uma longevidade considerável, com o Sol estimado em cerca de 10 bilhões de anos de idade e aproximadamente na metade de sua vida útil.',
  },
  {
    title: 'O Sol irá morrer?',
    text: 'Acima falamos que o Sol está na metade de sua vida útil, isso significa que em um futuro distante, assim como qualquer estrela, o sol irá "morrer", mas isso não é tão simples quanto parece, e também não será rápido. O Sol está atualmente em sua fase principal, mas com o tempo, o estoque de hidrogênio no núcleo do Sol diminuirá, e ele começará a fundir hélio em elementos mais pesados. Isso resultará em um aumento na temperatura do núcleo e em uma expansão da camada externa do Sol, ou seja, ele irá ficar maior, deixando de ser uma anã amarela, e se transformará em uma gigante vermelha, uma fase em que engolirá os planetas mais próximos, incluindo a Terra.<br><br>Durante a fase de gigante vermelha, o Sol perderá parte de sua massa para o espaço, criando uma nebulosa planetária, que ao longo do tempo irá se dispersar, misturando-se com o meio interestelar ao seu redor. Eventualmente, o núcleo restante do Sol se contrairá para formar uma anã branca, uma estrela pequena e densa composta principalmente de carbono e oxigênio. A anã branca não possui mais fusão nuclear ocorrendo em seu núcleo, ao invés disso, ela emite luz e calor provenientes da energia térmica remanescente de sua fase anterior, quando era uma gigante vermelha. Ao longo do tempo, a anã branca gradualmente esfria e diminui sua luminosidade, tornando-se uma "anã branca fria", isso significa que a estrela irá se apagar gradualmente. Esse processo levará trilhões de anos, e até lá provavelmente a humanidade não existirá.<br><br>Abaixo, a imagem da nebulosa planetária Anel do Sul, registrada pelo telescópio James Webb.',
    image: 'https://tm.ibxk.com.br/2022/07/13/13091559429066.jpg',
  },
  {
    title: 'Missões',
    text: 'Atualmente existem 19 missões da NASA ativas estudando o sol, e mais 13 missões em planejamento. A mais famosa delas é a Sonda Solar Parker, que em 2021 foi a primeira a "tocar" o Sol, chegando mais perto da estrela do que qualquer outra sonda. A missão tem estudado de perto o vento solar e os campos magnéticos no ambiente próximo ao Sol. Isso ajuda a compreender melhor a origem e a dinâmica do vento solar, assim como a interação entre o campo magnético solar e o campo magnético terrestre, além disso, tem registrado dados sobre a temperatura da coroa solar, erupções solares e ejeções de massa da coroa solar, eventos que têm impacto no clima espacial próximo à Terra.<br><br>Estudar o Sol é importante para entender o impacto das atividades solares na Terra, que podem afetar comunicações, redes elétricas e sistemas de navegação. Além disso, a pesquisa solar pode ajudar a entender mais sobre a formação e evolução estelar. Abaixo, imagens registradas pela Sonda Parker, ao se aproximar do sol.',
    image: 'https://www.nasa.gov/wp-content/uploads/2021/12/wispr_image.jpg',
  },
];
