import { ContentItem } from '../../default/default-page/Icontent-item';

export const CONTENT_LIST: ContentItem[] = [
  {
    title: 'Por que a Terra?',
    text: 'A Terra é um planeta singular em nosso sistema solar, apresentando condições ideais para sustentar a vida como conhecemos. A presença fundamental do Sol desempenha um papel crucial nesse equilíbrio. A energia solar é essencial para o funcionamento dos ecossistemas terrestres, fornecendo luz e calor. A distância moderada da Terra em relação ao Sol permite temperaturas adequadas para a existência de água no estado líquido, possibilitando a formação e manutenção de oceanos, rios e lagos, que desempenham um papel vital na sustentação da vida.<br><br>Além do Sol, a Lua desempenha um papel significativo na estabilidade do planeta. As interações gravitacionais entre a Terra e a Lua contribuem para a estabilidade do eixo de rotação da Terra, e para a desaceleração gradual da rotação da Terra, além de ser responsável pelas marés devido à atração gravitacional que exerce sobre os oceanos. Em geral, sem a lua, a Terra provavelmente seria um local inóspito e não poderia abrigar vida.<br><br>A combinação única desses fatores cria um ambiente propício para a vida prosperar. Essas condições favoráveis permitem o desenvolvimento e a evolução de uma incrível variedade de seres vivos, tornando a Terra um lugar verdadeiramente especial.',
  },
  {
    title: 'A origem da vida',
    text: 'A Terra é o nosso lar, e abriga uma diversidade enorme de seres vivos, mas nem sempre o planeta foi o lugar perfeito para abrigar vida, como é hoje. Inicialmente, a Terra era um lugar inóspito e incandescente, com intensa atividade vulcânica e constantes colisões de corpos celestes. Durante centenas de milhões de anos, o planeta passou por um período chamado de Bombardeio Intenso Tardio, no qual grandes asteroides e cometas atingiam a superfície, moldando a topografia e contribuindo para a formação dos oceanos. <br><br>À medida que o tempo avançava, a Terra começou a esfriar e formar uma crosta sólida. Os oceanos originaram-se a partir da água liberada por vulcões em erupção. Após essa fase, o planeta, então, entrou em um estágio mais estável, e foi nesse período que surgiram as primeiras formas de vida: organismos unicelulares simples que se desenvolveram nos oceanos primitivos. Esses microorganismos adaptaram-se às diferentes fases da Terra e evoluíram ao longo de bilhões de anos, dando origem à formas de vida mais complexas, como plantas e animais marinhos.<br><br> A Terra já abrigou diversos animais incríveis, que foram extintos ao longo do tempo, bem antes dos seres humanos existirem. As primeiras espécies humanas surgiram em um período relativamente recente, há cerca de 2 milhões de anos. Ao longo do tempo, várias espécies do gênero Homo coexistiram, algumas delas evoluindo e outras eventualmente desaparecendo. O Homo sapiens, espécie à qual pertencemos, é mais recente ainda, surgiu entre 200 e 300 mil anos atrás no continente africano, e possui uma série de características anatômicas e comportamentais distintas, incluindo um cérebro grande e a capacidade de criar ferramentas complexas, que contribuíram para a nossa evolução até aqui.',
  },
  {
    title: 'Missões',
    text: 'A Terra é um dos planetas mais estudados e monitorados, afinal, entendendo a origem e a dinâmica da vida em nosso planeta, é possível compreender mais sobre as características que nos trouxeram aqui, e quais os locais possíveis no espaço para que a vida evolua assim como evoluiu em nosso planeta. Além disso, podemos entender como cuidar do nosso planeta, e quais mudanças ele vem sofrendo.<br><br>Algumas missões vêm acontecendo na Terra, e temos diversos satélites em órbita, com diferentes propósitos. A NASA, por exemplo, conduz a missão Earth Observing System (EOS), que consiste em uma série de satélites equipados com instrumentos avançados para monitorar a atmosfera, os oceanos, a geologia e a cobertura vegetal da Terra. Esses satélites ajudam os cientistas a compreenderem as mudanças climáticas, a dinâmica dos oceanos e os padrões de vegetação.<br><br>Além dos estudos sobre a Terra, temos estudos acerca do ser humano, e como nos adaptaríamos a uma vida fora daqui, em outros locais do espaço. Um exemplo disso é a Estação Espacial Internacional (ISS), que orbita a Terra e serve como um laboratório espacial habitável e colaborativo.<br><br>Lançada em módulos ao longo de vários anos, a ISS é uma parceria internacional envolvendo agências espaciais de diversos países, incluindo a NASA (Estados Unidos), Roscosmos (Rússia), ESA (Agência Espacial Europeia), JAXA (Agência Japonesa de Exploração Aeroespacial) e CSA (Agência Espacial Canadense). Sua contrução foi finalizada em 2011, e desde então os astronautas e cosmonautas a bordo conduzem experimentos em diversas áreas, incluindo biologia, física, ciência dos materiais e medicina, aproveitando o ambiente de microgravidade para estudar fenômenos que não seriam possíveis na Terra. Tripulações rotativas de astronautas e cosmonautas passam períodos prolongados na estação, contribuindo para o entendimento humano sobre a vida e o trabalho no espaço, além de fornecer dados valiosos para futuras missões de exploração espacial.<br><br>A ISS viaja a mais de 28 mil km/h, e opera a cerca de 420 km acima da Terra. A imagem abaixo mostra a estrutura da estação espacial.',
    image:
      'https://img.olhardigital.com.br/wp-content/uploads/2023/08/estacao-espacial-internacional.jpg',
  },
];
